supinfo_commander_homepage:
    path:     /
    defaults: { _controller: SupinfoCommanderBundle:Default:index }

supinfo_commander_help:
    path:     /help
    defaults: { _controller: SupinfoCommanderBundle:Default:help }

supinfo_commander_login:
    path:     /login
    defaults: { _controller: SupinfoCommanderBundle:Default:login }

supinfo_commander_logout:
    path:     /logout
    defaults: { _controller: SupinfoCommanderBundle:Default:logout }

supinfo_commander_cart:
    path:     /cart
    defaults: { _controller: SupinfoCommanderBundle:Default:cart }

supinfo_commander_accept_cookies:
    path:     /accept_cookie
    defaults: { _controller: SupinfoCommanderBundle:CookieLaw:acceptLawCookie }

supinfo_commander_admin_login:
    path:     /gestion
    defaults: { _controller: SupinfoCommanderBundle:Admin:login }

#admin
supinfo_commander_admin:
    path:     /gestion/index
    defaults: { _controller: SupinfoCommanderBundle:Admin:index }

supinfo_commander_back_website:
    path:     /gestion/website
    defaults: { _controller: SupinfoCommanderBundle:Admin:website }

supinfo_commander_settings_infos:
    path:     /gestion/settings/informations
    defaults: { _controller: SupinfoCommanderBundle:Settings:informations }

supinfo_commander_administration_maintenance:
    path:     /gestion/admin/maintenance
    defaults: { _controller: SupinfoCommanderBundle:Administration:maintenance }

#Employés
supinfo_commander_administration_employees:
    path:   /gestion/admin/employees
    defaults: { _controller: SupinfoCommanderBundle:Employees:employees }

supinfo_commander_administration_add_employee:
    path:   /gestion/admin/employee/add
    defaults: { _controller: SupinfoCommanderBundle:Employees:addEmployee }

supinfo_commander_administration_delete_employee:
    path: /gestion/user/delete/{id}
    defaults: { _controller: SupinfoCommanderBundle:Employees:deleteEmployee }

supinfo_commander_administration_edit_employee:
    path: /gestion/user/edit/{id}
    defaults: { _controller: SupinfoCommanderBundle:Employees:editEmployee }

#Clients

supinfo_commander_administration_customers:
    path:   /gestion/customers
    defaults: { _controller: SupinfoCommanderBundle:Customer:customers }

supinfo_commander_administration_delete_customer:
    path:   /gestion/customers/delete/{id}
    defaults: { _controller: SupinfoCommanderBundle:Customer:deleteCustomer }

supinfo_commander_administration_activate_customer:
    path:   /gestion/customers/activate/{id}
    defaults: { _controller: SupinfoCommanderBundle:Customer:activateCustomer }

supinfo_commander_administration_view_customer:
    path:   /gestion/customers/view/{id}
    defaults: { _controller: SupinfoCommanderBundle:Customer:viewCustomer }