supinfo_commander_homepage:
    path:     /
    defaults: { _controller: SupinfoCommanderBundle:Default:index }

supinfo_commander_help:
    path:     /help
    defaults: { _controller: SupinfoCommanderBundle:Default:help }

supinfo_commander_login:
    path:     /login
    defaults: { _controller: SupinfoCommanderBundle:Default:login }

supinfo_commander_logout:
    path:     /logout
    defaults: { _controller: SupinfoCommanderBundle:Default:logout }

supinfo_commander_cart:
    path:     /cart
    defaults: { _controller: SupinfoCommanderBundle:Default:cart }

supinfo_commander_accept_cookies:
    path:     /accept_cookie
    defaults: { _controller: SupinfoCommanderBundle:CookieLaw:acceptLawCookie }

supinfo_commander_admin:
    path:     /gestion
    defaults: { _controller: SupinfoCommanderBundle:Admin:index }

