supinfo_commander_homepage:
    path:     /
    defaults: { _controller: SupinfoCommanderBundle:Default:index }

supinfo_commander_help:
    path:     /help
    defaults: { _controller: SupinfoCommanderBundle:Default:help }

supinfo_commander_login:
    path:     /login
    defaults: { _controller: SupinfoCommanderBundle:Default:login }

supinfo_commander_logout:
    path:     /logout
    defaults: { _controller: SupinfoCommanderBundle:Default:logout }

